# Cloud Build configuration for clinvar-ftp-watcher
#
# Command line test usage:
# gcloud builds submit --project=clingen-dev --config ./cloudbuild/docker-build-dev.cloudbuild.yaml \
#  --substitutions=COMMIT_SHA="testbuild" .

# Builds genegraph and tags for dev image repository
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '.', '-t', 'clinvar-ftp-watcher:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'clinvar-ftp-watcher:$COMMIT_SHA', 'gcr.io/clingen-dev/clinvar-ftp-watcher:$COMMIT_SHA']

# push the images
images:
  - 'gcr.io/clingen-dev/clinvar-ftp-watcher:$COMMIT_SHA'

# timeout in seconds
timeout: 2700s
